# Generated by Django 3.1.8 on 2021-05-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventories', '0002_auto_20210508_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Stock',
        ),
    ]
